PEtab-dev/libpetab-python

petab/observables.py, petab/parameters.py
Check that placeholder parameters are only considered as such for either observable *or* noise formula
Closes AMICI-dev/AMICI#1470
=> Fix get_required_parameters_for_parameter_table

petab/lint.py, petab/parameter_mapping.py, petab/problem.py
... in case those are fixed values and noiseFormula consists only of one single parameter.
=> Parameter mapping: Add option to ignore time-point specific noiseParameters

petab/problem.py, petab/yaml.py
- feel free to suggest a better name than `yaml_centric`
- not sure if it should default to relative paths when calling `petab.Problem.to_files` and/or `petab.yaml.create_problem_yaml` (currently only the former)
=> Optional relative paths in generated YAML

petab/measurements.py, tests/test_lint.py
So far it was allowed to not specify overrides for observable/noise parameter placeholders. Not sure why that was the case, as it is explicitly disallowed in the (current) PEtab specification.
Fixes #63
=> petablint: require overriding of observable/noise placeholder parameters

petab/problem.py
Usage example for `petab.Problem.to_files_generic`:
```python
petab_problem_custom = petab.Problem.from_yaml(...)
petab_problem_custom.condition_df = ...
petab_yaml = petab_problem_custom.to_files_generic('my/output/path')
petab_problem = petab.Problem.from_yaml(petab_yaml)
```
Useful for applications involving many PEtab problems that are generated as customisations of some original PEtab problem.
Could rename to e.g. `to_folder`
---
Usage example for the new argument `prefix_path` in `petab.Problem.to_files`:
```python
petab_problem.to_files(
sbml_file='model.xml',
condition_file='conditions.tsv',
measurement_file='measurements.tsv',
parameter_file='parameters.tsv',
observable_file='observables.tsv',
visualization_file='visualizations.tsv',
yaml_file='problem.yaml', …
```
=> Convenience method to quickly output PEtab problem to files

petab/lint.py
if there is no finiteness check for upper bound, I don't see why we should prevent lower bound 0 for log scale parameter, it convenient for specifying unbounded parameters after all.
=> allow zero bounds for log parameters

petab/visualize/plotter.py
Setting matplotlib rcParams makes it impossible to use custom styles, and therefore, should best be avoided.
=> Visualization: Don't mess with rcParams

petab/conditions.py, petab/core.py, petab/measurements.py, petab/observables.py, petab/parameters.py, petab/problem.py, petab/sbml.py, petab/yaml.py, tests/test_combine.py, tests/test_conditions.py, tests/test_measurements.py, tests/test_observables.py, tests/test_parameters.py
=> Add support for pathlib for reading PEtab tables

.github/workflows/ci_tests.yml
~Waiting for https://github.com/sbmlteam/libCombine/issues/46~
=> Run tests also on Python3.10

.github/workflows/ci_tests.yml, petab/core.py, petab/problem.py, petab/visualize/data_overview.py, petab/visualize/plotter.py, petab/yaml.py, tests/test_petab.py, tests/test_simulate.py, tests/test_visualization_data_overview.py, tests/test_yaml.py
* Run test suite on windows-latest, macos-latest, ubuntu-latest
* Fixed various issues related to temporary files on Windows
* Add support for pathlib.Path to some functions missed in #93 
* Fix loading remote yaml files on Windows
Closes #80
=> GHA: Run tests on windows-latest, macos-latest, ubuntu-latest

.github/workflows/ci_tests.yml
Python version was previously ignored for caching. Should avoid GHA warnings and speed up jobs.
=> GHA: Fix caching

petab/visualize/data_overview.py
* Fix number of conditions
* Handle optional preequilibrationConditionId
=> Fix petab.visualize.data_overview.create_report

petab/visualize/plotter.py
Remove [matplotlib.axes.Axes.relim](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.relim.html) which ignores error bars ("At present, Collection instances are not supported.")
Fixes #74
=> Vis: Fix cropped errorbars

petab/core.py
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
=> Fix pandas deprecation warning

petab/sbml.py, tests/test_sbml.py
New function `petab.get_model_for_condition` to generate condition-specific SBML models based on a PEtab problem.
=> Generation of condition-specific SBML models

petab/parameter_mapping.py, petab/sbml.py
RateRules were ignored so far...
Related to https://github.com/PEtab-dev/PEtab/issues/539, https://github.com/PEtab-dev/PEtab/issues/513
=> Fix SBML Rule handling logic

petab/measurements.py
cf. https://github.com/PEtab-dev/libpetab-python/pull/114
=> Method to check if measurement time is at steady-state

petab/measurements.py
e.g. avoids errors when simulating a timecourse period with no measurements
=> Create dummy simulation conditions dataframe for empty measurements

petab/measurements.py, petab/problem.py, petab/sbml.py, tests/test_sbml.py
Removes obsolete and deprecated functions from when observables were defined inside SBML models and when there was no observable table.
=> Remove deprecated functions related to sbml-observables

.github/workflows/ci_tests.yml
=> CI: Run tests only with min+max supported Python version

petab/visualize/plotting.py
* Don't use deprecated pandas.DataFrame.append
* Concatenate all at once
=> Speedup visspec assembly / fix deprecation warning

petab/problem.py
Handle missing model, missing parameter table.
Incomplete `petab.Problem`s are allowed by `__init__`, so it makes sense to also support that via `from_yaml`.
Useful for saving intermediate stages when creating PEtab problems.
=> Handle incomplete PEtab problems in `petab.Problem.from_yaml`

petab/parameter_mapping.py, tests/test_parameter_mapping.py
In such cases, the parameter value from the model should be used.
So far, NaN was kept.
=> Fix handling of NaN values for parameters in condition table

petab/problem.py, tests/test_petab.py
Allows specifying different conditions in different files.
Closes #7
=> Add support for PEtab problems with multiple condition files

petab/parameters.py
=> get_parameter_df: Allow any collection of parameter tables

petab/parameters.py, tests/test_parameters.py
When reading in parameter tables using `parameters.get_parameter_df`:
- check all parameter tables (not just those resulting from several parameter files) for contradicting parameter definitions
- remove the removal of duplicate parameters, will instead raise `ValueError`
- ensure that parameters that only differ by their `parameterId` are recognized as distinct and not dropped (fix #154 )
- adjust/extend `test_parameters.py` accordingly
=> Fix use of multiple parameter files

.github/workflows/ci_tests.yml, petab/C.py, petab/lint.py, petab/problem.py, petab/schemas/petab_schema.v2.0.0.yaml, petab/yaml.py
Add candidate schema for PEtab version 2. Choose the appropriate schema for validation. Add information on PEtab extensions to `petab.Problem` (currently as simple dict as provided in the yaml config).
Does not include `required` attribute for extensions yet (has to wait for https://github.com/PEtab-dev/PEtab/pull/545).
=> Add candidate schema for version 2 

petab/core.py, petab/problem.py
=> Fix typehints and deprecation warning

petab/models/sbml_model.py, petab/sbml.py
Fixes #166 (double logging)
Fixes #167 (ignoring severity)
=> Fix SBML validation

doc/modules.rst, petab/simplify.py, tests/test_simplify.py
Adds some functions to simplify / clean existing PEtab problems:
* removing unused conditions
* moving parameters that aren't really condition-dependent from the conditions table to the parameters table
=> Simplification of PEtab problems

petab/visualize/plotter.py
If there are no measurements for a plot, don't try to plot measurements.
Also provides more informative messages if plotting fails.
=> Vis: Handle missing data more gracefully

.github/workflows/ci_tests.yml
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> GHA: Replace deprecated `set-output`

petab/C.py, petab/lint.py, petab/petablint.py, petab/visualize/lint.py, setup.py, tests/test_visualization.py
Some basic validation of visualization files. Closes #8, closes  #1.
=> Add validation for visualization files

petab/sbml.py, tests/test_sbml.py
Handle parametric initial concentrations for cases where the initial concentration parameter does not occur in the model, but only in the parameter table.
=> Fix get_model_for_condition

petab/simulate.py, tests/test_simulate.py
What's your opinion on whether to default to `measurement` or `simulation`? Either is fine for me. Currently I am in favor of keeping `measurement`, because:
- I have mostly used this for synthetic data generation
- It won't break user code
However, I see that `simulation` might be what users expect from a simulator.
see also: AMICI-dev/AMICI#2050 and AMICI-dev/AMICI#2051
=> Simulator: rename measurement column to simulation

petab/calculate.py, petab/lint.py, petab/observables.py, tests/test_lint.py, tests/test_observables.py
Make sure symbols like `N`, `beta`, ... are used as scalar symbols, and not as sympy functions with the same name.
See also https://github.com/ICB-DCM/pyPESTO/issues/1048
=> Fix sympy symbol name clashes

petab/models/pysb_model.py
Incorrectly returned the parameter name, instead of its value.
=> Fix PySBModel.get_parameter_value

.github/workflows/deploy.yml
No need for long-lived API tokens anymore. see https://docs.pypi.org/trusted-publishers/
=> GHA/pypi: trusted publishing

petab/visualize/lint.py
=> Fix missing inplace=True in validation of visualization tables

petab/visualize/__init__.py
Only import plotting functions in `petab.visualize` if matplotlib is installed.
Closes #212
=> Make validate_visualization_df work without matplotlib installation

petab/visualize/plotting.py
Currently, there is no easy way to change figure sizes when using high-level visualization functions such as `plot_problem`.
Generally, I'd prefer controlling plotting through matplotlib's `rcParams`, but this change provides at least some backwards-compatible means of changing figure sizes at a higher level by, e.g. `petab.visualize.plotting.DEFAULT_FIGSIZE = (8, 4)`.
=> Customizable figure size

petab/problem.py, tests/test_petab.py
It doesn't seem to be quite clear if the `nominalValue` column needs to be present if all parameters are estimated.
However, since it's allowed to leave `nominalValue` empty, which is treated as NaN, it seems to make sense to treat a missing  `nominalValue` column as all-NaN.
See also https://github.com/ICB-DCM/pyPESTO/issues/1104
=> Handle missing nominalValue in Problem.get_x_nominal

.flake8, petab/calculate.py, petab/simplify.py, petab/visualize/data_overview.py, petab/visualize/lint.py, tests/test_conditions.py, tests/test_lint.py, tests/test_petab.py
Fixes #224 and a bunch of other pandas 2.1.0 FutureWarnings.
=> Fix pandas 2.1.0 FutureWarnings

petab/visualize/data_overview.py
Fixes a bug in petab.visualize.data_overview.create_report which fails if there is no preequilibrationConditionId column in the measurements table.
=> Fix accessing preequilibrationConditionId without checking for presence

petab/parameters.py, petab/problem.py, petab/sampling.py, tests/test_petab.py
Allow passing a list of parameter IDs to startpoint sampling for subsetting/reordering parameters.
=> Startpoint sampling for a subset of parameters

petab/visualize/plotter.py
=> Vis: fix replicates sorting

petab/core.py, tests/test_petab.py
... again.
Fixes an error when trying to apply re.sub to numeric values:
```
petab.flatten_timepoint_specific_output_overrides(problem)
build/venv/lib/python3.9/site-packages/petab/core.py:290: in flatten_timepoint_specific_output_overrides
observable[target] = re.sub(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pattern = 'observableParameter([0-9]+)_obs_a'
repl = 'observableParameter\\1_obs_a__10__c0', string = 1, count = 0, flags = 0
def sub(pattern, repl, string, count=0, flags=0):
"""Return the string obtained by replacing the leftmost
non-overlapping occurrences of the pattern in string by the
replacement repl.  repl can be either a string or a callable;
if a string, backslash escapes in it are processed.  If it is
a callable, it's passed the Match …
```
=> Fix flatten_timepoint_specific_output_overrides

petab/visualize/lint.py
=> Fix pandas FutureWarning in petab/visualize/lint.py

setup.py
Avoids
```
.tox\unit\lib\site-packages\pandas\__init__.py:249: in <module>
warnings.warn(
E   DeprecationWarning:
E   Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
E   (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
E   but was not found to be installed on your system.
E   If this would cause problems for you,
E   please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
```
=> Require pyarrow

tests/test_visualization.py
Fixes
```
_________________ ERROR collecting tests/test_visualization.py _________________
tests/test_visualization.py:112: in <module>
def visu_file_Fujita_empty():
.tox/unit/lib/python3.9/site-packages/_pytest/mark/structures.py:357: in __call__
store_mark(func, self.mark)
.tox/unit/lib/python3.9/site-packages/_pytest/mark/structures.py:422: in store_mark
warnings.warn(MARKED_FIXTURE, stacklevel=2)
E   pytest.PytestRemovedIn9Warning: Marks applied to fixtures have no effect
E   See docs: https://docs.pytest.org/en/stable/deprecations.html#applying-a-mark-to-a-fixture-function
```
https://github.com/PEtab-dev/libpetab-python/actions/runs/7691314124/job/20956434711
=> Fix pytest.PytestRemovedIn9Warning / Marks applied to fixtures

petab/parameter_mapping.py
Add None as default value, due to optionality.
=> Typehint states it is optional, but no default value is provided.

.github/workflows/ci_tests.yml, doc/conf.py, petab/calculate.py, petab/conditions.py, petab/core.py, petab/measurements.py, petab/models/model.py, petab/observables.py, petab/parameters.py, petab/problem.py, petab/sampling.py, petab/sbml.py, petab/simulate.py, petab/visualize/data_overview.py, petab/visualize/plotting.py, pyproject.toml, setup.py, tests/test_lint.py, tests/test_parameters.py, tests/test_petab.py, tests/test_simulate.py, tests/test_visualization.py, tests/test_visualization_data_overview.py, tox.ini
Follow-up to #251 
* Manual changes for compatibility with selected ruff rules
* run pre-commit hooks on GHA instead of flake8
* run tests on python3.12
=> maint: fix code style, check on gha

petab/visualize/plotter.py
Allow changing the default line style and markers for line plots.
(I'd also prefer to change the default to points-only (no line) for the measurements, but that's up for discussion.)
=> Vis: Make line plot markers configurable

.github/workflows/ci_tests.yml, .readthedocs.yaml, README.md, setup.py
Require python>=3.10 according to [NEP-0029](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule).
=> Require python>=3.10

petab/conditions.py, petab/mapping.py, petab/observables.py, petab/parameters.py
Only really important for the conditions table probably, because there you get some column named `index` that fails `petablint`.
=> Drop an index if it's reset

petab/schemas/petab_schema.v1.0.0.yaml, petab/schemas/petab_schema.v2.0.0.yaml
Avoid repetitions in yaml schema.
=> Simplify yaml schema

petab/petablint.py
I think the main use case is running petablint on a full petab problem, so we don't need the option to pass individual tables. To support individual tables with the upcoming petab v2, we'd have to extend the list of files and require a version number. I don't it's worth maintaining this functionality (correct me if I am wrong), since validation of individual files is anyways rather limited.
Therefore, this adds deprecation warnings to command line arguments for individual PEtab tables and for the `-y` `--yaml` flags, which are no longer required, and the removal of which will make `petablint` easier to use.
Related to https://github.com/PEtab-dev/libpetab-python/issues/271
=> Deprecate petablint with individual tables

petab/lint.py
The validation function was there, but was never called...
=> Validator: check prior parameters

petab/problem.py, petab/yaml.py, tests/test_yaml.py
More readable, testable, modular, and will be required in other places soon.
=> Refactor Problem.from_yaml, extract get_path_prefix

petab/v1/problem.py, petab/v1/yaml.py, tests/v1/test_yaml.py
Actually load files instead of just checking `exists`, which failed on remote files.
Closes #286
=> Fix validation for remote files

doc/modules.rst, petab/petablint.py, petab/v2/lint.py, petab/v2/problem.py, petab/versions.py, tests/v2/test_problem.py
For petab.v2, refactor the current validation setup to 
* be more modular
* allow PEtab extensions to register additional validation steps in the future
* make validation messages accessible programmatically (previously, they were logged directly)
Also:
* Make `petablint` work with both v1 and v2 problems.
* Add first validation rules that are specific to v2
=> New validation API

petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_conversion.py, tests/v2/test_problem.py, tox.ini
Converter for PEtab v1 problems to PEtab v2 problems. 
Allows converting a set of PEtab v1 files to v2 files or creating a petab.v2.Problem from v1 yaml file.
To be extended/adapted as v2 matures.
Closes #272.
=> PEtab v1 to v2 converter

petab/__init__.py
Fixes an issue introduced in #297, which made all optional dependencies required.
=> Fix imports

doc/modules.rst, petab/v1/C.py, petab/v2/C.py
For now, mostly a copy of v1. The be updated as petab v2 development progresses.
Also adds some missing documentation.
Use of PEtab v2-related constants from `petab.v1.C` is deprecated.
:eyes: https://petab--299.org.readthedocs.build/projects/libpetab-python/en/299/build/_autosummary/petab.v2.C.html
=> Add petab.v2.C

petab/v1/visualize/plotting.py
- Use `copy` of conditions DataFrame for inplace sorting
- closes #304
=> Circumvent `SettingWithCopyWarning`

doc/modules.rst, petab/v1/priors.py
petab.v1.priors was not included in the documentation.
=> doc: add petab.v1.priors

petab/v1/models/pysb_model.py
If no ID is given, use `pysb.Model.name` as fallback. As is already the case for SbmlModel and its `id` attribute.
=> Make model id optional for PySBModel

petab/v1/problem.py, petab/v2/problem.py, tests/v1/test_petab.py, tests/v2/test_problem.py
When passing the problem configuration as `dict` to `Problem.from_yaml`, one should be able to specify the base path for resolving relative paths. See #324.
Closes #324
=> Enable passing the base path to Problem.from_yaml

petab/v1/models/sbml_model.py, petab/v1/sbml.py
This PR allows to create SBML models from string, but more critically considers an SBML model with warnings still as valid SbmlModel. The current PEtab implementation considers a file with warnings as invalid SBML, which is not the case.
=> Sbml model enhancements

petab/v1/mapping.py, petab/v1/problem.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v1/test_petab.py, tests/v2/test_mapping.py, tests/v2/test_problem.py
Add functions for adding individual conditions/observables/parameter/measurements to Problem. This will simplify writing test cases and interactively assembling petab problems.
`petab.v2.Problem.add_*` will be added / updated to the new format separately.
Related to #220.
=> Functions for adding conditions/observables/parameter to Problem

doc/modules.rst, petab/schemas/petab_schema.v2.0.0.yaml, petab/v2/C.py, petab/v2/__init__.py, petab/v2/experiments.py, petab/v2/lint.py, petab/v2/problem.py, pytest.ini, tests/v2/test_experiments.py, tests/v2/test_lint.py, tests/v2/test_problem.py
Related to https://github.com/PEtab-dev/PEtab/issues/586
* constants for new yaml fields / table columns / ...
* read/write experiment table
* add experiments table to Problem, and populate from yaml
* add first validation functions
* include missing modules in API docs
To be complemented by separate pull requests.
=> Add constants + I/O + validation for new conditions/experiments tables

tests/v1/test_priors.py
Fixes an issue in `test_priors_to_measurements` which led to evaluating the prior at the wrong parameter values (using the location parameter of the prior instead of the actually estimated parameters). The problem was in the test code, not the tested code.
=> Fix test_priors_to_measurements

petab/v1/models/sbml_model.py, pyproject.toml, tests/v1/test_combine.py, tests/v1/test_deprecated.py, tests/v1/test_lint.py, tests/v1/test_observables.py, tests/v1/test_parameter_mapping.py, tests/v1/test_petab.py, tests/v1/test_sbml.py, tests/v1/test_simplify.py
Simplify creating a PEtab SbmlModel from antimony files / strings.
Replace simplesbml by antimony in tests.
=> Add `SbmlModel.from_antimony`

petab/v1/problem.py, pyproject.toml
Introduces `Problem.config` which contains the info from the PEtab yaml file.
Sometimes it is convenient to have the original filenames around.
Pydantic gives more helpful error messages than `jsonschema` in case of incorrect inputs. Later on, this could replace  `jsonschema` completely.
If accepted, I will add the same for `petab.v2.Problem`.
Related to #324.
=> Store problem configuration in Problem

petab/v2/problem.py
Introduces `v2.Problem.config` which contains the info from the PEtab yaml file. The same as #326, but for `v2.Problem`.
=> Store problem configuration in `v2.Problem`

petab/v1/__init__.py, petab/v1/lint.py, petab/v1/parameters.py, petab/v2/C.py, petab/v2/__init__.py, petab/v2/_helpers.py, petab/v2/conditions.py, petab/v2/lint.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_conversion.py, tests/v2/test_problem.py, tox.ini
Update creation of PEtab problems, validation, conversion from v1 to v2,... to the new long condition table.
Many TODOs remain. To be continued after #337.
=> v2: Adapt to long conditions table

petab/v1/priors.py
Previously, missing `*PriorParameters` would have resulted in a KeyError.
=> Fix Prior.from_par_dict for missing priorParameters columns

petab/petablint.py, petab/versions.py
Don't show `Support for PEtab2.0 and all of petab.v2 is experimental` warning when validating PEtab v1 problems.
Import `petab.v2.*`  only when needed.
=> Fix petablint v2 warning

petab/v1/calculate.py, petab/v1/problem.py, petab/v2/C.py, petab/v2/__init__.py, petab/v2/lint.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_problem.py
Add basic support for PEtab version 2 experiments (see also https://github.com/PEtab-dev/PEtab/issues/586, and  https://github.com/PEtab-dev/PEtab/pull/581). Follow-up to #334.
Partially supersedes #263, which was started before petab.v1/petab.v2 were introduced and before https://github.com/PEtab-dev/PEtab/issues/586.
* updates the required fields in the measurement table
* updates some validation functions to not expect the old `simulationConditionId`s (but does not do full validation yet)
* extends PEtab v1 up-conversion to create a new experiment table.
=> Support for petab v2 experiments

petab/__init__.py
Fixes this nonsensical warning:
> E   DeprecationWarning: Accessing `petab.v2` is deprecated and will be removed in the next major release. Please use `petab.v1.v2` instead.
=> Fix v2 import Deprecation warning

petab/v1/calculate.py
For computing residuals, ... from measurement + simulation tables, we need to match the corresponding rows. Previously, this was done using a subset of PEtab measurement table columns and checking whether all values in these columns match.
This changes it to using the full set of overlapping columns, not only the known measurement columns.
With that, the same functions can be used for PEtab v2 measurement/simulation tables.
=> petab.calculate: compare all common columns

petab/v1/problem.py, petab/v2/problem.py
Change the `estimated` argument in Problem.add_parameter to `estimate` to match the column name.
=> Problem.add_parameter: Rename kwarg estimated->estimate

petab/v1/problem.py, petab/v1/yaml.py, petab/v2/problem.py, petab/versions.py, tests/test_version.py
Add function for parsing version numbers. Update checks.
Fixes #349.
=> Fix version checks

petab/v2/lint.py, petab/v2/petab1to2.py
* don't create unnecessary experiment tables
* write yaml file *after* updating the config dict
* check for missing experiments
* handle anonymous experiments
=> v2: fixes to validation and upconversion

petab/v1/problem.py, petab/v2/petab1to2.py, petab/v2/problem.py
* add to_yaml
* refactor model, avoid extra elements in object tree
* use ProblemConfig in petab1to2
=> Update/use ProblemConfig

petab/v2/C.py, petab/v2/core.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_core.py, tests/v2/test_problem.py
Implement an object model for the various PEtab entities as an alternative to working with the plain DataFrames.
Related to #337.
Object names are very likely to change. This is more of a proof of concept.
Also adapt to recent changes in https://github.com/PEtab-dev/PEtab/pull/581
=> v2: Observable/conditions/experiments/... objects

petab/v2/core.py
=> Fix deprecated class Config in pydantic models

doc/conf.py, doc/modules.rst, petab/v1/visualize/plotting.py, petab/v2/core.py, pyproject.toml, pytest.ini
:eyes: https://petab--360.org.readthedocs.build/projects/libpetab-python/en/360/build/_autosummary/petab.v2.core.html
=> doc: petab.v2.core

petab/v1/math/SympyVisitor.py, petab/v1/math/sympify.py, tests/v1/math/test_math.py
So far, when math expressions were parsed, they were evaluated as far as possible. This was not always desirable.
Now, this optional as far as conveniently possible.
Closes #363.
=> Add `evaluate: bool` argument to math parser

petab/v2/core.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_problem.py
* Update serialization
* Update upconversion
* Update tests
=> v2: Parameter.estimate -> bool

petab/v2/C.py, petab/v2/core.py, petab/v2/problem.py
* priorDistribution/priorParameters instead of separate initializationPrior&objectivePrior
* additional prior distributions
Related to https://github.com/PEtab-dev/libpetab-python/issues/374.
=> v2: Adapt models to changes in prior distributions

petab/v2/core.py, petab/v2/lint.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_core.py
* Check priors (related to https://github.com/PEtab-dev/libpetab-python/issues/374)
* Check observables
* Fix missing prior parameters after v1->v2 conversion of uniform priors
* Fix some pydantic validation / serialization 
* Fix style
=> v2: More validation

petab/v1/simulate.py
Previously, `petab.v1.simulate.sample_noise` silently ignored `observableTransformation`. For example, in case of observableTransformation=log and noiseDistribution=normal, it incorrectly sampled from a normal instead of a log-normal distribution.
Fixes https://github.com/PEtab-dev/libpetab-python/issues/382.
=> Handle `observableTransformation` in `petab.v1.simulate.sample_noise`

petab/v2/C.py, petab/v2/core.py, petab/v2/petab1to2.py, tests/v2/test_core.py
Adapt to the changes in https://github.com/PEtab-dev/PEtab/pull/625.
Placeholders are now listed explicitly.
Closes https://github.com/PEtab-dev/libpetab-python/issues/390.
=> v2: Update to new observable placeholder specification

petab/v2/lint.py
There is already `CheckMeasuredObservablesDefined`.
=> v2: Remove redundant CheckAllObservablesDefined

petab/schemas/petab_schema.v2.0.0.yaml, petab/v2/C.py, petab/v2/petab1to2.py, petab/v2/problem.py, tests/v2/test_problem.py
Adapt to https://github.com/PEtab-dev/PEtab/pull/641.
=> v2: parameter_file -> parameter_files

petab/v1/priors.py
The check only looked for whether it was not a string, but empty string values that are passed as `""` were not caught here. This should fix the error.
=> Allow empty string "" in columns to be overridden with default values in priors

petab/v2/core.py, tests/v2/test_core.py
Easier access to changes associated with a given period, and measurements associated with a given experiment.
=> Add `v2.Problem.get_{changes_for_period,measurements_for_experiment}`

doc/modules.rst, petab/v2/converters.py, petab/v2/core.py, tests/v2/test_core.py
DRY
Introduce `BaseTable` to implement common functionality of `{Observable,Parameter,...}Table`.
=> Refactor `v2.*Tables`

petab/v1/math/printer.py, tests/v1/math/test_math.py
Power expressions with non-atomic bases or exponents were not printed correctly. Fixed here.
=> Fix PetabStrPrinter for powers

petab/v2/core.py, tests/v2/test_core.py
Add  `Experiment.sorted_periods` and extend tests.
=> Add `Experiment.sorted_periods`

petab/v1/sbml.py
Create output directory in `write_sbml` if necessary.
=> `write_sbml`: mkdir

petab/v2/core.py, tests/v2/test_core.py
Measurements don't require an experiment ID. Therefore, make `experimentId` optional in `Problem.add_measurement`. Also, require keyword arguments there.
=> Optional `experimentId` in `Problem.add_measurement`

petab/v2/core.py, tests/v2/test_core.py
One-liner to check that a given `Problem` is valid.
=> Add `Problem.assert_valid`

petab/v2/lint.py, tests/v2/test_lint.py
Check for undefined experiments referenced in the measurement table.
Closes #434.
=> v2 linter: check measurement.experimentId

petab/v2/C.py, petab/v2/core.py, petab/v2/lint.py, tests/v2/test_lint.py
After https://github.com/PEtab-dev/PEtab/pull/645, any condition that is used as a first condition cannot refer to any symbols other then the parameters listed in the parameter table, or `time'.
Closes https://github.com/PEtab-dev/libpetab-python/issues/424.
=> Update v2 condition table `targetValue` validation

petab/v2/converters.py, pyproject.toml, tests/v2/test_converters.py
Due to https://github.com/PEtab-dev/PEtab/pull/645 ...
* ... the first period of a PEtab experiment has to be applied before initial assignments are evaluated. That means, the changes have to be implemented as initial assignments instead of event assignments at the initial timepoint (or any pre-existing initial assignments would have to be included in the event assignment).
* ... for any subsequent periods, the event assignments need to be modified. Compartment-size changes in PEtab no longer follow the SBML event assignment semantics. That means, we need event assignments for all concentration-based species inside such a compartment to preserve concentrations instead of amounts.  
Closes #452.
=> Update `ExperimentsToEventsConverter` to changed initialization semantics
