PEtab-dev/libpetab-python

petab/lint.py, tests/test_lint.py
allowing inconsistent typing makes it much more "interesting" to implement new features.
=> fix noise formula check

doc/example/example_Isensee/Isensee_visualizationSpecification.tsv, doc/example/example_Isensee/Isensee_visualizationSpecification_replicates.tsv, petab/visualize/plotter.py, petab/visualize/plotting.py, tests/test_visualization.py, tests/test_visualization_new_structure.py
add possibility to plot more points for simulations than for measurements
=> Smooth simulation

petab/measurements.py, tests/test_petab.py
Closes PEtab-dev/libpetab-python#61
=> Lint: Check for valid parameter IDs in observable/noise parameters

petab/lint.py, tests/test_lint.py
=> Linter: Check condition IDs are unique

.github/workflows/ci_tests.yml
Previous settings worked only on linux and macos...
=> GHA: Fix cache directory on Windows

tests/test_visualization.py, tests/test_visualization_new_structure.py
Should fix somewhat randomly occurring matplotlib/tk failures
=> Switch to matplotlib agg backend for tests

MANIFEST.in
Add missing non-python files to package
=> Fix MANIFEST.in, add missing files

.github/workflows/ci_tests.yml
To detect any missing files or import issues
=> GHA: Regular package installation instead of -e

.ci_pip_reqs.txt, setup.py
- https://github.com/jupyter/nbconvert/issues/1736
- https://github.com/AMICI-dev/AMICI/pull/1742
=> fix jinja version

petab/measurements.py
=> petablint: Fix incorrect noise-parameter-mismatch error messge

petab/petablint.py, petab/problem.py
Also remove the respective `-n` option from `petablint` and remove `Problem.from_folder`.
=> Remove ancient/deprecated default file naming scheme

.github/workflows/ci_tests.yml, README.md, setup.py
* State python support policy
* Remove Python 3.7 checks from GHA
=> Python support policy

petab/problem.py, tests/test_petab.py
Add `Problem.sample_parameter_startpoints_dict` for sampling startpoints as parameter_id=>parameter_value dicts.
=> Startpoints as dict

petab/problem.py
model_file parameter was not properly handled, resulting in missing model files in the created yaml file.
=> Fix Problem.to_files(model_file=...)

petab/core.py
For coherence with other `get_XXX_df` functions.
=> Handle DataFrame/None as input to `get_visualization_df`

petab/problem.py, tests/test_petab.py
Makes it more convenient to compute model selection criteria.
=> Add petab.Problem.n_{estimated,measurements,priors}

petab/calculate.py, petab/lint.py, petab/math/__init__.py, petab/math/sympify.py, petab/models/sbml_model.py, petab/observables.py
Centralize sympification of PEtab and SBML math expressions.
Simplifies incorporating https://github.com/PEtab-dev/libpetab-python/pull/260
Also fixes likely collisions of SBML model entities with sympy entities.
=> Refactor sympification

.pre-commit-config.yaml, petab/calculate.py, petab/composite_problem.py, petab/conditions.py, petab/core.py, petab/lint.py, petab/mapping.py, petab/measurements.py, petab/models/model.py, petab/models/pysb_model.py, petab/models/sbml_model.py, petab/observables.py, petab/parameter_mapping.py, petab/parameters.py, petab/problem.py, petab/sampling.py, petab/sbml.py, petab/simulate.py, petab/visualize/data_overview.py, petab/visualize/helper_functions.py, petab/visualize/plot_data_and_simulation.py, petab/visualize/plot_residuals.py, petab/visualize/plotter.py, petab/visualize/plotting.py, petab/yaml.py, pyproject.toml, tests/test_parameters.py, tests/test_petab.py, tests/test_simulate.py
=> Ruff pyupgrade: python3.10

MANIFEST.in, pyproject.toml, setup.py
Further transition from setup.py to pyproject.toml where easily possible.
=> setup.py -> pyproject.toml

petab/v2/models/__init__.py, petab/v2/models/model.py, petab/v2/models/pysb_model.py, petab/v2/models/sbml_model.py
=> Add petab.v2.models
